### PR TITLE
Pull Request: Add Stationary-Base Demo (2nd attempt)

### PR DESCRIPTION
**Pull request by erichlof**
This PR updates the README.md file to reflect the new Stationary Base addition as well as how to use it.  

It also adds a Stationary Base demo as well as a StationaryBaseDemo.js dependency file.  My StationaryBaseDemo.js dependency file is located in the newly created 'js' folder.

I changed the dependencies in the script src tags inside my StationaryBaseDemo.html file so that they will go and find the dependencies that are publicly hosted, instead of creating extra copies inside this repository.  These outside dependencies are virtualjoystick.js (which will be found locally in this Master) , three.min.js (which will be found hosted publicly from threejs.org) , and threex.keyboardstate.js (which will be found at jeromeetienne.github.io which is publicly hosted by GitHub).

Thanks!
-Erich

### CODE REVIEW

**Comment by jeromeetienne** [comment]
seems good :) can you add virtualjoystick.js tho ? without it, your example wont work

**Comment by erichlof** [comment]
Yes, would like me to add virtualjoystick.js to the 'js' folder that I created?

**Comment by jeromeetienne** [comment]
@erichlof no need but thanks for asking :)

**Comment by jeromeetienne** [comment]
reopened, i closed it by mistake

**Comment by erichlof** [comment]
Hi @jeromeetienne 

What would you like me to do with virtualjoystick.js ?  I can either link to it from my html file (as I already have done) and it will hopefully find it because it is hosted by Github on your jeromeetienne.github.io page.  

Or I can change your virtualjoystick.js on your gh-pages if it needs to be updated.  I'm confused as to which file my demo will try to find if I just put src = virtualjoystick.js in my demo html .  Is it looking for the Master version or the gh-pages version (which is 8 months old and outdated?).

How should I change the line: 
script src="virtualjoystick.js"></script  to find the right file?  Or just leave it alone and change the gh-pages virtualjoystick.js ?

Sorry for the confusion.  I'm a newbie at PR's :)

**Comment by jeromeetienne** [comment]
you got me confused for sure :) ok i will merge it by hand. but the info i need is **what did you modify in virtualjoystick.js** without that i can't check your modification are ok.

Where can i get this info ? how can i know what you modified in `virtualjoystick.js`

**Comment by erichlof** [comment]
Sorry for the confusion.  Let me try to explain:
My demo requires the current version of virtualjoystick.js that lives in the Master branch of your repository.  No changes are needed.  I did not make any recent changes to virtualjoystick.js

The confusion is coming from my side.  I thought that we needed to also make your gh-pages branch version of virtualjoystick.js match the Master version of virtualjoystick.js.  The Master version is already updated and correct from my last PR.  You already merged those stationary-joystick-base changes,  so no further action is necessary for the Master branch.

If you go to this link:
https://github.com/jeromeetienne/virtualjoystick.js/blob/gh-pages/virtualjoystick.js

You will see that this version is 9 months old.  This is fine if you want it to be that way.  I thought my demo would look here and I don't think this is the case now.  I have been trying to educate myself about 'branches' and github.io hosted pages.   I was probably mistaken and confused. :)

Could you merge and try the demo out when it is available through your hosted pages (usually 10 minutes wait period)?  Maybe it will work with no further changes?

Edit: I am just trying to add a simple demo.  I did not change anything inside virtualjoystick.js .  I also updated the README.md so that people could see how to use stationary base in the opts. object.  Hope this makes sense :)

**Comment by jeromeetienne** [comment]
oh got it! merged at last :) thanks again for your contribution

**Comment by jeromeetienne** [comment]
i just made some file reorganisations, you may have to pull

**Comment by jeromeetienne** [comment]
@erichlof i just looked at your github. i love http://erichlof.github.io/ about 3d programming :)

you may be interested in threex i think http://jeromeetienne.github.io/threex/

those are extension modules for three.js, very usefull when writing games. i would be interested to know what you think

**Comment by erichlof** [comment]
Hi @jeromeetienne ,

Thanks so much for merging this!  Your solution is perfect - thank you for putting my .js file inside my demo's html file.  I should have thought of that.  :)

Also thanks for taking a look at my GitHub!  It's an ambitious project/goal to start teaching 3D game programming from scratch (it's also for newbies to general programming concepts, such as 'what is an 'if' statement?').  Three.js is such a wonderful and enabling tool, that I wanted to show people how they can get simple games going without any low-level stuff.  My ultimate goal is to show how to make about 5 games from scratch, each getting more complex than the last.  We'll see if I can find the time to complete this task!  :)

Yes of course I will use your threex libraries because they are perfect for games!  I am already using threex.keyboardstate.js (which is the best helper file for the keyboard on the net!), and now virtualjoystick.js for the controls if playing on mobile.  I'm also interested in your threex.cannon.js, threex.skymap.js, threex.geometricglow.js and possibly threex.godrays.js .  I have already linked to and talked about your awesome helpers on my 3DGameProgramming.blogspot.com .

I come from a C background on Windows, making about four 3D games using OpenGL and C back around the year 2000.  They are under the author name of BinaryBrotherz (with a z).  You can Google my old games' screenshots here:
http://3dgameprogramming.blogspot.com/2013/09/a-short-history.html
  My games were titled GladiaTron3D, Virtual Bombard,  3D Asteroid Patrol, and Deep Space Pong.  I no longer have hosting for these and they are offered on some East European servers for 'free games'.  Three.js being actively developed is what got me going again with hobby game programming.  There are WAY more tools and helpers today than there were for me back in 2000.  I wish I had some of these tools back then - that's why I decided to start the blog.

Anyway, enough about my story - Thanks again for all your work Jerome!  Guys like you make GitHub and open-source programming truly awesome!
Take care,
-Erich

**Pull request merged**
