### PR TITLE
Updated README.md and added 2 Demos for limitStickTravel

### PR DESCRIPTION
**Pull request by erichlof**
This PR updates the README.md to reflect the new limitStickTravel feature as well as how to use it.  

This PR also adds 2 demos to your examples folder.  One is showing limitStickTravel and the other is the same but this time with Stationary Base enabled.

### CODE REVIEW

**Comment by jeromeetienne** [comment]
excelent! thanks agaibn

**Comment by erichlof** [comment]
@jeromeetienne 
Hi Jerome, thanks for merging.  I noticed however that the new demos (LimitStickTravelDemo.html and LimitStickTravelDemoStationaryBase.html) aren't located in your github.io pages so they are not working when you click on them.  It says 'there isn't a page here'.  Maybe if you place them in the 'examples' folder on your gh-pages, it will work?

Thanks again!
-Erich

**Comment by jeromeetienne** [comment]
My bad. I just forgot to push them. I will do tomorrow. If i forget just
ping me again :)

**Comment by erichlof** [comment]
Ok thanks Jerome! :)

**Pull request merged**
